AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions and api endpoints for twalstats
Resources:
  GetReadings:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetReadings
      CodeUri: s3://twalstats-package/99c04e3e433ff25d1caaca7fa225e64e
      Handler: index.handler
      MemorySize: 128
      Timeout: 300
      Runtime: nodejs12.x
